tests_zeeguu_api/test_feeds.py, zeeguu_api/api/__init__.py, zeeguu_api/api/feeds.py, zeeguu_api/api/search.py, zeeguu_api/api/topics.py, zeeguu_api/api/user_articles.py, zeeguu_api/api/user_languages.py
Added:
- user language endpoints 
- search (instant, filter and subscription) endpoints 
- topic subscription and filter endpoints
The Travis build is not passing as it will build with the master branch of the core, which is not up to date with the search functions yet.
=> Api search endpoints

requirements.txt, zeeguu_api/api/translate_and_bookmark.py, zeeguu_api/api/translator.py, zeeguu_api_test/test_possible_translations.py, zeeguu_api_test/test_translations.py
@mircealungu please have a look over it.
It provides the exact same functionality as the old version, nothing changed with this PR. It only integrates Zeeguu-API with APIMUX.
=> Integrate APIMUX in Zeeguu-API

zeeguu_api/api/translator.py
Wordnik doesn't provide the same service as the other
translators. This means that it does not provide
relevant information for the multiplexer.
This patch moves Wordnik translator into another
apimux object.
=> Split APIs into two apimux objects

zeeguu_api/api/teacher_dashboard.py
Added methods enabling seeing the users reading_session activity. This allows us to see the user activity even if there are no bookmarks related to the session
=> Teacher dashboard

zeeguu_api/api/teacher_dashboard.py
This pull request adds 2 new endpoints to the API:
1. An "upload file" endpoint which takes some information about an article, and creates it in the database. This function also creates a map between the cohort where the article was added, and the article id (this is to only display articles for a given class on a class page). 
2. An endpoint to delete previously uploaded articles if the person attempting deletion has access to the cohort associated with the article being deleted.
=> Upload / deletion of articles for teacher dashboard

zeeguu_api/api/translator.py
Currently Wordnik doesn't need A/B testing since there
is only one service that provides the definition functionality.
This commit uses A/B testing flag to detect when
multiple Wordnik api keys are passed and to load
balance between them.
=> Enable round robin for Wordnik translator

zeeguu/core/model/language.py
=> Polish is repeated in CODES_OF_LANGUAGES_AVAILABLE_AS_NATIVE

tools/recompute_missing_reading_sessions.py, zeeguu/core/model/user_reading_session.py
Uses the old logic based on the events tracked in the database to create the user sessions
=> Code to update the missing sessions from the extension update

zeeguu/core/elastic/elastic_query_builder.py
We were expecting a Keyword to add user topics to the filter the user topics selected.
=> Fix ElasticSearch Topic Search

start.py, zeeguu/api/endpoints/accounts.py, zeeguu/core/account_management/user_account_creation.py
Iga needs to add a user account w/o languages. So we created an /add_basic_account endpoint for that.
=> Adding basic account creation

zeeguu/core/model/personal_copy.py
+ Filter saved articles based on user's learned language.
=> + Filter saved articles based on user's learned language.

zeeguu/core/account_management/user_account_creation.py
This pull request includes the code to only set default preferences with productive exercises enabled for new users who register with the invite code for the learning cycle feature.
=> productive exercises enabled by default for new users with the feature

tools/migrations/24-05-21--add_uuid_to_session.sql, zeeguu/api/endpoints/accounts.py, zeeguu/api/endpoints/sessions.py, zeeguu/api/test/fixtures.py, zeeguu/api/test/test_account_creation.py, zeeguu/api/test/test_teacher_dashboard.py, zeeguu/api/utils/route_wrappers.py, zeeguu/core/model/session.py
code works for me. can you test @tfnribeiro ?
=> Hardening user session management

zeeguu/api/endpoints/user_articles.py, zeeguu/core/content_recommender/__init__.py, zeeguu/core/content_recommender/elastic_recommender.py, zeeguu/core/elastic/elastic_query_builder.py, zeeguu/core/model/user_article.py
1. New articles like function in elastic-recommender that uses user likes to recommend articles like what they have already explicitly liked 
2. New endpoint for /foryou  
**This PR is combined with a PR in zeeguu-web, they should be approved together https://github.com/zeeguu/web/pull/371**
=> FEATURE: content based filtering 

tools/send_subscription_emails.py
Combined the keywords into a single email body:
Should avoid spamming users emails if they have multiple searches.
=> Combined keywords into a single email

zeeguu/api/endpoints/user_preferences.py, zeeguu/core/model/user_preference.py
Add the settings of the reader to the user_preferences table.
=> Allow tracking of user preferences in reader

tools/report_generator/data_extractor.py, tools/report_generator/generate_report.py
- The report was not considering articles that were outside the report range for the user top articles.
- Report the Avg time spent reading the article per users.
- Added a line stating where the file has been written to at the end of the report generation.
=> Top Opened Articles not considering articles outside range

setup.py
Workflow was failing due to punkt_tab requirement to run some of our tests.
=> Tests were failing due to lack of installation of punkt_tab

zeeguu/api/endpoints/user.py, zeeguu/core/model/user_activitiy_data.py
Updates to use the moment library to display how much time as passed from the reading session.
Web PR: https://github.com/zeeguu/web/pull/493
=> 189 1 hour ago seems a bit disingenuous when i just left the article

tools/report_generator/data_extractor.py, tools/report_generator/generate_report.py
Added tracking to what Keywords are being filtered / added in order to add sources that fit our users preferences.
=> 196 report should we have subscribed topics report

tools/_playground.py
To a link with an actual \<article\> tag
=> Change plaground article

tools/send_subscription_emails.py
I made some more changes to the email formatting:
Added some of the Zeeguu colours and removed some of the <p> tags to see if the spacing is better in the final rendering.
=> Formatting Changes Email

tools/send_subscription_emails.py
- Removed styling from the link to the source
- Made the Article info with parenthesis after the title
=> Change the formatting of the searches email

zeeguu/api/endpoints/search.py
- Avoid situations where the deletion of the search breaks due to FK constraints.
=> Check both Subscriptions and Filters

tools/mysql_to_elastic_new_topics.py
- Added comment describing the parameters for the script.
@mircealungu I made the script index 5k documents per default (I think that's a good number for a dev default)
=> Added comment for clarity

tools/es_v8_migration/set_url_keywords_article.py, tools/mysql_to_elastic_new_topics.py
- Fixed totals on the mysql_to_elastic
- Filtered articles already mapped to keywords.
=> Fixes to the Auxiliary V8 Scripts

tools/es_v8_migration/set_url_keywords_article.py
Filter the ids in python not mysql
=> Fix, filter in python rather than SQL

tools/es_v8_migration/migrate_old_topics_to_new_topics.py, zeeguu/api/endpoints/topics.py, zeeguu/core/model/new_topic.py
- Added the migration script for Old Topics
- Show topics that are available in the language (as opposed to all topics)
=> 273 create mapping from old topics to new

zeeguu/api/endpoints/user_articles.py, zeeguu/core/model/personal_copy.py
- Updated endpoint to allow for pagination of the saved articles for a user.
Functionality implemented in Web PR: https://github.com/zeeguu/web/pull/628
=> Added support for pagination for saved articles.

zeeguu/core/model/url_keyword.py
@tfnribeiro - i found this change uncommitted on my machine.
please double-check that the comment is correct. tka!
=> updated comment

README.md
I have added the steps I took to connect and load the database in DBeaver if you are setting up the api with Docker to the Read Me file. I thought it might be helpful for other students working on the project.
=> steps to connect and load db in DBeaver

tools/migrations/24-10-23--delete_bookmark_learned.sql, tools/old/fix_bookmark_learned_status.py, tools/old/past_exercises_for_user.py, zeeguu/core/bookmark_quality/top_bookmarks_for_user.py, zeeguu/core/model/bookmark.py, zeeguu/core/model/user.py, zeeguu/core/sql/learner/exercises_history.py, zeeguu/core/sql/learner/words.py, zeeguu/core/sql/queries/words_to_study.sql, zeeguu/core/word_scheduling/adaptive/scheduling_algo.py, zeeguu/core/word_scheduling/basicSR/basicSR.py
- Replaced all the instances where bookmark.learned was used. Now, we check for the datetime in learned_time, if it exists, then the bookmark has been learned.
- Tested the different endpoints (execises, history, updating the bookmark learned status) and it results in expected behaviour.
=> Remove bookmark.learned boolean as its redundant with learned time

tools/report_generator/data_extractor.py, tools/report_generator/generate_report.py
- Report topic generation method got overridden when changing the topic names.
=> Fix report generation

zeeguu/api/utils/translator.py
As far as I can tell, even if I define the configuration to be 
```
MULTI_LANG_TRANSLATOR_AB_TESTING=False
```
the current code makes it True anyway. 
the current PR should fix that.
=> more human readable updates for exercise sessions

zeeguu/api/endpoints/feature_toggles.py, zeeguu/core/definition_of_learned/is_learned.py, zeeguu/core/model/bookmark.py, zeeguu/core/model/user_preference.py, zeeguu/core/test/test_bookmark.py, zeeguu/core/word_scheduling/basicSR/basicSR.py, zeeguu/core/word_scheduling/basicSR/learning_cycle_SR.py, zeeguu/core/word_scheduling/basicSR/levels_SR.py
Can you have a look at this @tfnribeiro ?
=> New exercise scheduling removing a bit of duplication and possibly fixing bug

setup.py, zeeguu/core/tokenization/stanza_tokenizer.py
- Fixed path to be reachable
- In case the coordinates of the paragraph are null then use 0.
=> Fixes to Stanza model

zeeguu/api/endpoints/bookmarks_and_words.py, zeeguu/api/endpoints/exercises.py
Matches the changes in https://github.com/zeeguu/web/pull/719
=> Updated API calls to correctly get with_tokens

zeeguu/core/model/language.py
- Changed available languages call to show the languages we are actively crawling in the backend.
=> Available Languages reports languages crawled.

zeeguu/core/model/language.py
- Swedish code is "sv" not "se"
=> Fixed wrong code

zeeguu/api/endpoints/translation.py
- With the changes from sending a form to json, there is no longer a need to parse a string to a boolean.
=> Fixed Left and Right ellipsis coming in as None

zeeguu/core/model/language.py
- Removed danish that was duplicated.
=> Added Spanish to Crawled Languages

zeeguu/api/endpoints/user_articles.py, zeeguu/core/content_recommender/elastic_recommender.py
- Recommendations for homepage are now 15 articles + 5 videos
=> Updated count of videos + articles

tools/old/past_exercises_for_user.py, tools/reduce_number_of_studied_bookmarks.py, zeeguu/api/endpoints/exercises.py, zeeguu/api/endpoints/user_notifications.py, zeeguu/api/endpoints/user_preferences.py, zeeguu/core/exercises/similar_words.py, zeeguu/core/model/bookmark.py, zeeguu/core/model/search.py, zeeguu/core/model/user.py, zeeguu/core/model/user_preference.py, zeeguu/core/test/test_bookmark.py, zeeguu/core/word_scheduling/basicSR/basicSR.py
Cleaning up some of the endpoints for bookmark scheduling. 
Added support for a MAX_WORDS_TO_SCHEDULE preference and updated the scheduling algo accordingly.
=> Scheduler using the "Max Words In Learning" user preference 

tools/reduce_number_of_studied_bookmarks.py, zeeguu/api/endpoints/exercises.py, zeeguu/core/exercises/similar_words.py, zeeguu/core/model/user.py, zeeguu/core/word_scheduling/basicSR/basicSR.py
- updated reduce_number_of_studied_bookmarks.py to keep all the words that are above level 2 or more; we keep their schedule;
- by default we add 20 words as max words to study
=> - added /bookmarks_next_in_learning

.gitignore, zeeguu/api/endpoints/bookmarks_and_words.py, zeeguu/core/model/user.py
Added one endpoint for fetching weekly practiced words.
=> Added endpoint

zeeguu/api/endpoints/bookmarks_and_words.py
- Fixed bookmark deletion. When no quality bookmarks remain, UserWord is marked as fit_for_study = False. In the future we will probably introduce a new synthetic bookmark
=> - Fixed fit_for_study(b.user_word) call

CLAUDE.md, requirements.txt, tools/migrations/25-07-08--add_meaning_frequency_and_phrase_type.sql, tools/update_meaning_frequencies.py, zeeguu/core/audio_lessons/script_generator.py, zeeguu/core/bookmark_quality/negative_qualities.py, zeeguu/core/model/ai_model.py, zeeguu/core/model/meaning.py, zeeguu/core/model/meaning_frequency_classifier.py, zeeguu/core/prompts/meaning_frequency_classifier.py
=> - migrations for adding meaning_frequency to the db
