zeeguu/api

- .travis.yml
- dashboard_test.cfg
Changed test dir for Travis, updated .travis.yml for submitting test results to dashboard.
> Sending test results from a Travis build to dashboard should work now

- .travis.yml
- collect_performance.py
- dashboard_test.cfg
- setup.py
- zeeguu_api/app.py
This should enable the new unit-test-grouping-by-endpoint functionality of the Dashboard to be used in the Zeeguu-API Travis integration.
The `dashboard_test.cfg` file in this PR does not contain the SUBMIT_RESULTS_URL option, which means that the test results will not be uploaded to the live deployment of the Dashboard. 
This way, unwanted Travis test results will not be displayed on the live Dashboard.
If the results should be uploaded to the live Dashboard again, simply adding the following line to the config file will do the trick:
`SUBMIT_RESULTS_URL=https://zeeguu.unibe.ch/api/dashboard/submit-test-results`
> Configuration for new Dashboard functionality

- zeeguu_api/api/translate_and_bookmark.py
- zeeguu_api/api/translator.py
This commit adds a way to enable A/B testing on
the APIs for quality control purposes.
Setting any value for the environment variable
ENABLE_A_B_TESTING for the zeeguu-api-core
container will now make get_all_translations
to return each API as a first result one by one.
> Add A/B testing support for APIs

- zeeguu/api/api/nlp.py
- zeeguu/core/nlp_pipeline/automatic_gec_tagging.py
- zeeguu/core/nlp_pipeline/confusion_generator.py
- zeeguu/core/nlp_pipeline/spacy_wrapper.py
- create_confusion_words: Instead of just providing the confusion words the dictionary is returned, and the frontend can use all the properties. This was done to support the user_activity
- added a new endpoint get_sentences_for_wo, which should implement the logic to find sentences when WO has a very long sentence. Currently, the highest similarity sentence with a limit of 15 tokens is used.
- Fixed the article, it was checking the wrong parameter to select the article used.
- Changed the names in the dictionary to make more sense.
- Added a method to get similarity of two sentences.
> Updates to nlp components

- zeeguu/api/endpoints/article.py
- zeeguu/core/model/personal_copy.py
Added an end-point similar to `make_personal_copy` called `remove_personal_copy` to delete saved articles. 
This end-point can be called from the Web to remove the saved articles.
> Adding end-point to remove saved articles

- .github/workflows/test.yml
From the docker deployment file:
`FROM python:3.9.2-buster`
Shouldn't we ensure the version is the same on the server? We could also upgrade python in the docker to the latest version? 
https://devguide.python.org/versions/ Seems like 3.9 ends in 2025, and since no errors are seen for 3.11 maybe we could just upgrade it?
> Match Workflow python version with deployed version

- dev.py
- requirements.txt
- zeeguu/api/app.py
- zeeguu/api/endpoints/teacher_dashboard/cohorts.py
- zeeguu/core/sql/query_building.py
- zeeguu/core/user_statistics/activity.py
- zeeguu/core/user_statistics/exercise_corectness.py
- zeeguu/core/user_statistics/exercise_sessions.py
- zeeguu/core/user_statistics/reading_sessions.py
We were quite behind with the dependency pinned to 1.3. The FMD was not compatible anymore. 
The changes are quite minor. 
Tagging you @tfnribeiro more to ask if you could test to see that it works for you and to attract your attention to the change in `db.session.execute` which now needs to take a `text()` around a query.
> Updating to sqlalchemy >= 2.0 

- zeeguu/core/emailer/zeeguu_mailer.py
Some exception would be thrown when the API doesn't have a flag emoji mapped. Return empty if none is found.
> Fix Zeeguu mailer

- zeeguu/core/model/article_difficulty_feedback.py
- zeeguu/core/model/user_article.py
- zeeguu/core/user_activity_hooks/article_interaction_hooks.py
We have changed the *find* function for ArticleDifficultyFeedback. This was done because we can see that feedback for the same article, by the same user, is stored multiple times in the database. Therefore, we are only interested in the newest feedback given by the user.
> Retrieve past article_difficulty_feedback for user.

- zeeguu/api/endpoints/accounts.py
- zeeguu/core/account_management/user_account_creation.py
- zeeguu/core/model/user.py
User creation is failing since UserPreference is trying to be added before we have commit the user to the user table, and therefor it can't be inserted into the UserPreference table as we have no user_id. Moved the initialization of the user to the `create_account` in `core\account_management\user_account_creation.py`
> Fix user creation

- zeeguu/core/feed_handler/feed_handler.py
- zeeguu/core/feed_handler/newspaperfeed.py
- zeeguu/core/feed_handler/rssfeed.py
- zeeguu/core/model/feed.py
Added a flag to the FeedHandler super class that allows skipping the extracting metadata call. This should only be called when the  feed is created, which at this point is done in feed.py line 81 `feed_handler = FEED_TYPE_TO_FEED_HANDLER[feed_type](url, feed_type)`. 
When crawling the websites to extract the data, this information is stored in the DB and therefor we do not need to re-acquire it. This is done during `initializeFeedHandler` where now the keyed argument **is_stored_db** is passed to skip the call to `extract_feed_metadata`.
+ Automatic formatting.
- Add a new feed and ensure the fields are updated. 
- Crawled the websites and checked the metadata wasn't retrieved.
> Allow DB Feeds to skip Metadata retrieval

- zeeguu/core/model/bookmark.py
- zeeguu/core/word_scheduling/basicSR/basicSR.py
+ Now whenever we perform a scheduler update, we check if the next_practice_time is above the current_time. If this is true, it means the word is being practiced before schedule. 
This would happen if a user kept doing in the Review Words screen for an article - overriding the scheduler.
+ Added a property, can_update_schedule, which allows the frontend to add logic around if the scheduler can update the word or not.
> Fix overriding schedule

- tools/migrations/24-05-06--update_cohort_language_to_null_for_testing.sql
- zeeguu/core/sql/learner/exercises_history.py
This pr allows the cohort language to be null, so teachers can see all exercises, regardless of the student's chosen language. It also includes a sql query to update the language of the cohort testing the learning cycle implementation to null.
> shows all exercises for test cohort no matter the language

- zeeguu/core/content_quality/quality_filter.py
Created issues where a parsed article would have different count of words when it's downloaded in the database. This resulted in some small paywalled articles being downloaded for FR.
> Fix a bug where splitting wasn't mirroring Articles

- zeeguu/api/endpoints/search.py
- zeeguu/api/endpoints/user_articles.py
- zeeguu/core/content_recommender/elastic_recommender.py
- zeeguu/core/elastic/elastic_query_builder.py
- zeeguu/core/language/strategies/flesch_kincaid_difficulty_estimator.py
- zeeguu/core/model/article.py
- zeeguu/core/model/user.py
- We are currently using a hard filter that might is a bit too restrictive considering we don't have many sources at extreme levels.
- Instead, I propose using a gaussian function from ES that considers both the difficulty and the recency of an article when suggesting it to a user.
- I divide the FK scale into 6 equal bands to represent each CEFR level, and search articles around the middle point of that band with a tolerance slightly above that of a level step (2.1 vs 1.6). In a concrete example, a A1 student will see articles in a band centered around 0.85 +/- 2.1. Before we would allow from 1 -> 5.5, which for a A1 student might be too hard. This scale makes the scoring slightly more nuanced and continuous, hopefully helping users filter out easier articles.
Visually, it can be …
> Changes to the ES filtering on difficulty

- tools/migrations/24-05-29--add_user_preference_to_bookmark.sql
- zeeguu/api/endpoints/bookmarks_and_words.py
- zeeguu/core/bookmark_quality/fit_for_study.py
- zeeguu/core/model/bookmark.py
- zeeguu/core/model/bookmark_user_preference.py
Changes to support: https://github.com/zeeguu/web/pull/392
- Supports functionality for the user to force a word to be presented in the exercises or not.
- This is handled by an extra column in the bookmark table that functions similarly to the Star interaction in the past.
**Question: Should we align the star interaction whenever the user adds a word to the exercises?**
> Updates to support user word preferences

- zeeguu/api/endpoints/search.py
When updating the Session handling, the _SearchSubscription_ was not taking the db_session as the first paramenter.
> Fixed adding interests

- zeeguu/core/elastic/elastic_query_builder.py
Just making this to re-enable the User Interests in case we want to test the functionality of adding user searches.
| No User Interests | With "dyr" (animal) in User Interests |
| -------- | ------- |
|![image](https://github.com/zeeguu/api/assets/17390076/dab39c88-4464-4343-93f9-e48f4a128a35) | ![image](https://github.com/zeeguu/api/assets/17390076/539b7927-7e4f-4963-8a23-0ff95f29e3da) |
> Re-introduce user interests in the recommendations

- zeeguu/api/endpoints/bookmarks_and_words.py
- zeeguu/core/bookmark_quality/fit_for_study.py
- zeeguu/core/definition_of_learned/__init__.py
- zeeguu/core/definition_of_learned/is_learned.py
- zeeguu/core/model/bookmark.py
- zeeguu/core/model/exercise.py
- zeeguu/core/model/exercise_outcome.py
- zeeguu/core/model/sorted_exercise_log.py
- zeeguu/core/test/test_bookmark.py
- zeeguu/core/word_scheduling/basicSR/basicSR.py
Includes fixes for the issues:
`ExerciseOutcome.free_text_feedback` was outdated, and most of the logic was handled in the Update part of the BasicScheduler. Which means even if the flag is set to 0, the user still sees it in the exercises. 
Since this is an outdated method, we don't really use it anymore, but for completion I provided a solution that checks for the set of characters in the outcome. If it contains the "expected" outcome letters, then it's not considered other feedback.  
Whenever the user toggles the words that are scheduled to not be studied anymore they need to be deleted from the scheduler. This was not done with the new UserPreference calls and was added. This is done by checking if the bookmark has a schedule associated in `BasicSRSchedule` and deleting it from that …
> Fixed FitForStudy flag

- zeeguu/api/endpoints/user.py
- zeeguu/core/model/user.py
- zeeguu/core/test/test_language.py
Changes to avoid conflicts when a user changes to a new language in the front-end settings. 
The issue involves changing to a language that the user has not studied and it can reliably cause a concurrency issue in the backend which also causes a failure at the front end.
To solve this, I made that whenever the endpoint is called from the frontend - all the updates are made in the same session and then committed, avoiding the concurrency. 
- Removed code that is not used anymore related to language_level_data.
- Whenever we call user.set_learned_language, we now can pass the cefr_level, to ensure the object is updated with the right level.
- Update test to also check for cefr_level when it's updated
https://github.com/zeeguu/web/pull/406
> Updated settings to avoid concurrency updates

- tools/migrations/24-08-15--fix_politikens_titles.sql
- zeeguu/core/content_retriever/article_downloader.py
Sometimes politikens feed will encode danish characters with strange characters, it only happens in the title which gets displayed in the home page for the users.
Difficult to test, as it only happens occasionally.
Would this be fine? I made the change just specifically for the feed with issues so it doesn't affect anything else.
> Fix Politikens Feed

- zeeguu/core/model/bookmark.py
When adding the consecutive_answers to the bookmarks we can run into exceptions if the bookmark as not been scheduled yet. In these cases, the value should be set to `Null` and this should fix the tests failing in the API. 
- We are not guaranteed that a bookmark has been trained and has consecutive answers. In this case, we should return null.
> Fix failing tests after change in Bookmarks

- setup.py
- zeeguu/core/content_retriever/__init__.py
- zeeguu/core/content_retriever/article_downloader.py
- zeeguu/core/model/article.py
- zeeguu/core/model/bookmark.py
This is the lines I think were the culprit.
If you look at the old `download_and_parse_with_remove_sents` the text would be stripped of all the repeating patterns that were used to distinguish if they are "paywalled" or not. 
To fix this, I renamed the method to reflect that we download and parse with readability, and then we text for the quality of the text before removing any patterns. 
One thing that I am not sure, is that now that we are storing the broken articles, should we then set the text to be what it was before the clean-up (in case we want to retrain the model later) or should we leave the clean text?
> Check for quality before performing clean-up

- tools/report_generator/generate_report.py
- I noticed that the report was not generating the activity report, this was due to the fact that there was an inner join based on the bookmarks reviewed. Now it should correctly display the total Bookmarks even if users do not review any of them.
- Title ordering.
| **Before** |
| :-: |
| ![image](https://github.com/user-attachments/assets/45a76f02-d001-424d-a9f6-e9ea3e9449f3) |
| **After** |
| ![image](https://github.com/user-attachments/assets/6f653b47-1619-469a-b501-543d52a894ea) |
> Fixes to Report

- zeeguu/core/model/user.py
- Seems the issue was due to the fact that the before date was initialized in the method's definition and would be cached. After a day of running, the API would only return the bookmarks before the day it was initialized.
> Fix Stale Date in the History Tab

- zeeguu/api/endpoints/search.py
- zeeguu/core/model/search_subscription.py
- Use total subscribers to a search to decide if the Search is empty and can be deleted safely from the DB without breaking FK constraints.
> Re-wrote a method to get total subscribers

- tools/migrations/24-08-30--user_cohort_map.sql
- zeeguu/api/endpoints/feature_toggles.py
- zeeguu/api/endpoints/student.py
- zeeguu/api/endpoints/teacher_dashboard/_common_api_parameters.py
- zeeguu/api/endpoints/teacher_dashboard/_permissions.py
- zeeguu/api/endpoints/teacher_dashboard/cohorts.py
- zeeguu/api/endpoints/teacher_dashboard/helpers.py
- zeeguu/api/endpoints/teacher_dashboard/student.py
- zeeguu/api/endpoints/user.py
- zeeguu/core/account_management/user_account_creation.py
- zeeguu/core/language/strategies/flesch_kincaid_difficulty_estimator.py
- zeeguu/core/model/__init__.py
- zeeguu/core/model/cohort.py
- zeeguu/core/model/user.py
- zeeguu/core/model/user_cohort_map.py
- zeeguu/core/model/user_exercise_session.py
- zeeguu/core/model/user_preference.py
- zeeguu/core/model/user_reading_session.py
- zeeguu/core/user_statistics/exercise_sessions.py
- zeeguu/core/util/text.py
Change to support the UI changes to allow multiple classrooms for one user (https://github.com/zeeguu/web/pull/526)
- Removed the `cohort_id` from the user table, instead a mapping table was introduced to track this relationship.
- The script first inserts all the `cohort_id` into the mapping table, so users remain in their current classrooms.
- Testing membership of users is now done by a method `is_member_of_cohort` which expects an ID and checks that mapping exists for the user.
- `basic_user_info` now sends a list of cohorts if the user is in multiple classrooms.
- Change methods to call their new equivalent, overall maintaining the same logic the end-points used to have. This mostly means that now we need to check for multiple entries and find if a specific ID is present.
- …
> 198 students invisible when joining second classroom

- tools/send_subscription_emails.py
- zeeguu/api/endpoints/search.py
- zeeguu/api/endpoints/user_articles.py
- zeeguu/core/content_recommender/elastic_recommender.py
- zeeguu/core/elastic/elastic_query_builder.py
Re-worked the priority given to the different parameters in the query.
- In the home page, we no longer use the should query to include the user searches, but instead do a small query to find if there are any relevant new articles which are then ordered with the general topic preferences and recency filter. The home page essentially prioritizes Topic > (Recency == Difficulty Level)
- Extended the Search endpoint to allow users to fine-control their searches. The user can use the UI to specify they'd rather see more relevant content at the cost of less recent articles or difficulty. 
The UI changes are implemented in:  https://github.com/zeeguu/web/pull/530
> 205 frontpage remains static for long

- tools/send_subscription_emails.py
Updated the text sent in the Notification Emailer so the user can see the titles of the new articles that have arrived. The articles themselves have an hyperlink to the website where they were found so the user can go there immediately. 
@mircealungu Would it be possible to just test it to see if the HTML works as expected before fully deploying it?
> 204 gmail detects the text contents to be the same and hides them in continuous emails

- tools/send_subscription_emails.py
- zeeguu/core/util/__init__.py
- zeeguu/core/util/reading_time_estimator.py
- The emails are now sent with information about the difficulty, source and read time.
To note, in the actual email the CSS will match that used by the service(?)
> Improved Article formatting to contain stats

- zeeguu/api/endpoints/user.py
- I realized the units weren't correct in the check. It should be in decimals (percentage) rather than int. - I can still see that sometimes I finish an article but it's still popping up in my feed, so maybe lowering it to 0.9 might be a good idea. @mircealungu has this ever occurred to you?
> Lower the threshold to show read articles.

- tools/migrations/24-09-24--adding-language-to-search.sql
- zeeguu/api/endpoints/search.py
- zeeguu/core/model/search.py
- zeeguu/core/model/search_filter.py
- zeeguu/core/model/search_subscription.py
- With the new subscription system if a user changes languages they would still see all the keywords that aren't really relevant for that language.
- This change seeks to store the language_id that the users were learning when they performed the search and they will only be retrieved if the user has that language set as current language.
I have tested this with a few languages in my local environment and it seems OK. However, I haven't got all the searches as I did some search deletion and as such there wasn't a lot of issues running the script. 
Some situations to look out for is people subscribed / filtering the same keyword with different languages, who do we pick? Do we just delete these and they can re-add it at some point?
> Added language_id to a search

- default_docker.cfg
- zeeguu/api/endpoints/feature_toggles.py
These "cohortless" invite codes seem to be added by using a config file, so you will have to add it in Production for it to work.
For now, I added the feature set under Merle's features (so the new exercises are available). I left a comment in the `feature_map.py` file to remember us that this invitation code is available and should be used to allow the latest features to be available.
> Adding general invitation code

- zeeguu/api/endpoints/user.py
- If no CEFR level is passed in the settings then the settings update to the user is not run. The reason for this was because we had issues before where if a user would switch languages the field for their level might go empty and that would cause some data corruption. Now, settings have been isolated and it's not possible to change language without setting a level. Meaning that this constraint shouldn't be in place (or at least should not require the frontend to always send the cefr_level).
- Instead of cancelling the user update if cefr_level isn't provided, instead no update is made to the learned_language if no cefr_level is provided.
> CEFR Level shouldn't be necessary in user settings

- tools/mysql_to_elastic.py
The script crashes if the DB is empty, as max_id and min_id is None and the loop can't iterate on them.
> Add 0 default to max and min id

- zeeguu/core/exercises/similar_words.py
- When introducing the filtered list, if the user has more than 10 words the method would fail since it would have an undefined variable.
- Fixed by making the final variable candidates so it matches both paths of the if statement.
@mircealungu I tested this and this seems to be the issue. When testing this change, I only called the API with an empty user so the error didn't show up - this should ensure we always have a valid word set to sample from.
> Fixed hanging when similar words is called

- tools/recompute_fk_difficulties.py
I've added a script to recompute FK scores for all the languages that just had new constants added, similar to https://github.com/zeeguu/api/blob/master/tools/old/recompute_fk_difficulties_for_polish.py.
> Script for recomputing FK scores for languages with new constants

- tools/mysql_to_elastic_new_topics.py
- tools/report_generator/data_extractor.py
- tools/report_generator/generate_report.py
- Improved the error reporting in the bulk inserts by printing the errors found and the total Success + Errors
- Added the URL keywords to report where any URL keywords seen more than 100 times with no Topic assigned will be shown in the table. 
Errors might have been due to the attempt to index broken articles with empty fields, which fail when adding to ES. To avoid these situations, I also filter the broken articles in the query now. I expect less errors now, but if we do we should get them printed out with some information about what was the cause.
> Add Error Reporting for ES Inserts + Add URL Keywords to Report

- zeeguu/api/endpoints/exercises.py
- zeeguu/core/model/user.py
- zeeguu/core/word_scheduling/basicSR/basicSR.py
We were retrieving all the bookmarks to start the exercises, which for users with many bookmarks would cause waiting times to start exercises (up to 15 seconds!). This would happen every time they start exercises, and there is no need to load all the available bookmarks. 
Instead, now the query only limits to the number of bookmarks requested by the frontend, and by default it's 100. This is used in the exercises, which can query up to 200 bookmarks, (100 scheduled and 100 unscheduled) which are then sorted and returned. This results in a reduction to about 1-2 seconds in my own server, which is OK for our purposes.
We still have an issue when users have many bookmarks and they go to the Words page, where all the bookmarks are loaded. In this case, maybe we could use pagination or …
> Improved Performance of Starting Exercises

- tools/migrations/24-11-04--updating-url-keyword-mapping.sql
Added mappings for a variety of url keywords.
- 'ekonomi' -> Business
- 'kunstmarkt' -> Culture & Art
- 'wintersport' -> Sports
- 'technik' -> Technology & Science
- 'buehne und konzert' -> Culture & Art
- 'bildung' -> Health & Society
- 'mode design' -> Culture & Art  @mircealungu  (or Health & Society?)
- 'krop sundhed' -> Health & Society
- 'naturvidenskab' -> Technology & Science
- 'boganmeldelser' -> Culture & Art
- 'wimbledon' -> Sports
- 'ep valg' -> Politics
- 'badminton' -> Sports
- 'superliga' -> Sports
- 'uddannelse' -> Health & Society
- 'kvindelandsholdet' -> Sports
- 'rummet' -> Technology & Science
- 'erhverv' -> Business
- 'sundhed' -> Health & Society
- 'valg i usa' -> Politics
- 'teknologi' -> Technology & Science
- 'sport auto' -> Sports
- 'entreprises' -> Business
- …
> Added new topics to url_keywords

- tools/crawl_summary/crawl_report.py
- tools/migrations/24-12-02--add_notification_table.sql
- tools/migrations/24-12-02--add_user_notification_table.sql
- zeeguu/api/endpoints/__init__.py
- zeeguu/api/endpoints/user_notifications.py
- zeeguu/core/model/notification.py
- zeeguu/core/model/session.py
- zeeguu/core/model/topic.py
- zeeguu/core/model/user_feedback.py
- zeeguu/core/model/user_notification.py
- Added two new tables, corresponding logic and enpoints to support sending notifications to the users on the web.
- Instead of get_server_time_utc() we should use datetime.now(), updated the instances where this wasn't the case.
> Add notification endpoint

- zeeguu/core/model/sorted_exercise_log.py
- zeeguu/core/test/test_bookmark.py
- The old implementation would generate random exercises until having at least a number of different dates. This doesn't really reflect what we expect. So instead, I have changed it to insert exercises with increasing cooldowns to reflect the behavior we expect from users. Currently, this increases 1 day per exercise. 
- Added a condition that the exercise only counts in the streaks if the dates are different.
> Fix failing tests with exercise outcomes

- zeeguu/api/endpoints/feature_toggles.py
- zeeguu/core/test/test_bookmark.py
- zeeguu/core/test/test_scheduling.py
- Now the default is the levels, so we need to update the tests to reflect that.
- I have also left the tests to the learning cycles. This requires a flag to turn off the levels for a user, since that's how the tests are setup. I introduced an invite code: 'learning-cycle' which has not used before and can be used to toggle between levels and learning cycles.
> Fixed Tests for Levels and Learning Cycles

- tools/get_lang_stats.py
- zeeguu/core/language/strategies/flesch_kincaid_difficulty_estimator.py
- FK uses Token Length / Syllables and Sentence length to compute the difficulty of a text. We will have cases where we don't have a formula for new languages. To make better "guesses" what is the best formula, we can use the script to find which language is closest given these metrics. TO DO, the weights are slightly different, so maybe those should also be reflected in the distance calculation.
- Fixes a value in the Russian Formula, and Polish now uses the Russian values rather than german.
- Portugal now uses the Spanish weights rather than the English ones.
| English Constants | Spanish Constants |
| :-: | :-: |
| ![image](https://github.com/user-attachments/assets/38c4248a-87af-4a2d-b8bb-b18cef2da379) | ![image](https://github.com/user-attachments/assets/43229a02-4014-44ac-93a8-1874f …
> FK Updates 

- zeeguu/api/endpoints/bookmarks_and_words.py
- We often delete bookmarks to create the fused bookmarks in the frontend. This enters in conflict with deleting the text since the context of the fuse bookmarks can be the same, and can be deleted during the process of the new bookmark creation since the translations have a delay. For this reason, instead of cleaning up orphaned texts on deletion, we should do it as a maintenance script to ensure the users do not run into occasions where they loose bookmarks.
> Removed deletion of texts

- zeeguu/core/test/test_tokenizer.py
- zeeguu/core/tokenization/stanza_tokenizer.py
- zeeguu/core/tokenization/token.py
- Found a case in French where the assumption that the apostrophe wouldn't be followed by a single character doesn't hold. Made that condition specifically for punctuation rather than a token in general.
"n'a" - should be a token, rather than "n'", "a".
> Update to tokenization

- README.md
"docker compose up" runs all containers, which breaks as there are multiple instances of zapi. It should therefore be "docker compose up zapi_dev_translations".
> Update ReadMe (container specification)

- zeeguu/core/model/user_activitiy_data.py
- zeeguu/core/model/user_reading_session.py
- zeeguu/core/util/__init__.py
- zeeguu/core/util/reading_time_estimator.py
- zeeguu/core/util/time_conversion.py
- We noted that especially in smaller articles our estimation based on the scrolling percentage can perform quite poorly (not showing small articles as read). Instead of using the scroll percentage, we now use the total duration the user has read the article. This was made to ensure that if the user is off by a few seconds opening the article can resolve that issue.
> Fix for extension not saving prgoress

- docker-compose.yml
- tools/evaluate_infer_topics.py
- tools/run_knn_classification_with_text.py
- tools/run_knn_similarity_search.py
- zeeguu/core/content_retriever/article_downloader.py
- zeeguu/core/elastic/elastic_query_builder.py
- zeeguu/core/model/new_text.py
- zeeguu/core/model/source.py
- zeeguu/core/model/source_text.py
- zeeguu/core/semantic_search/__init__.py
- zeeguu/core/semantic_search/elastic_semantic_search.py
- Updated docker compose to use the Zeeguu data + the Zeeguu resources to download the models/store ES data.
- Simplified the pipeline to be more generic and easier to use. This is to easily support the fact that we are going to have multiple sources in ES and not just articles.
- Now when calling the `build_elastic_semantic_sim_query_for_topic_cls`, we pass a text + ids we do not want to be used.
- I also simplified the call to get the Topic Object by creating the method  `get_topic_classification_based_on_similar_content`. This makes it more easily to re-use the same logic used for article inferance.
- Created a simple demo where a text is classified using the KNN classifier.
- Increased the number of candidates when retrieving the neighbours.
@mircealungu I realized I reverted this …
> Ml topic classification based on text

- zeeguu/core/model/article.py
- Fix error spotted in Sentry.
This led me to find an interesting point we should consider. Now, spammy articles that have a text we have encountered before are all linked to the same source, and there might be a case where in the past, they weren't considered as broken, but now they are. This will make it easier to spot these ocurrences.
> Fixed Source Broken Update

- tools/create_article_fragments_and_sources.py
- zeeguu/core/model/source.py
- Since the query was based off source_id being none, the offset was "skipping" articles as the starting article will always be the first article in the DB without a source id.
- Added an extra condition when finding a source that isn't broken but it's being attempted to be found with a broken flag. If this is the case, then we make it broken.
> Fix migration script

- requirements.txt
- tools/migrations/25-04-16--remove-vtt-from-video.sql
- zeeguu/core/model/video.py
- zeeguu/core/youtube_api/youtube_api.py
Change caption downloader to youtube-transcript-api instead of yt-dlp. This should not require login, and it seems to be faster as well.
https://github.com/jdepoix/youtube-transcript-api
TODO:
- Make sure all tables where text is stored have characterset utf8mb4 and collate utf8mb4_bin (I think this was done Monday)
- If this is working, the video_downloader.py needs to uncomment the rest of the topics. And the video_crawler should set the number of videos to 50.
> fix-caption-downloader

- zeeguu/api/endpoints/user_articles.py
- zeeguu/core/content_recommender/elastic_recommender.py
- zeeguu/core/elastic/basic_ops.py
- zeeguu/core/elastic/elastic_query_builder.py
- zeeguu/core/semantic_search/elastic_semantic_search.py
- Since we do not use article_id as the ElasticSearch ID, we now need to fetch the ids before running the more like this query.
> Fixed For You tab not working

- zeeguu/core/youtube_api/youtube_api.py
- Fix the bug where videos in the wrong language are not set as broken. The problem was that we didn't return after finding the video broken. Before we would still try to find captions for videos in the target language, and sometimes they would be available. Now we save the video as broken as soon as the wrong language is detected.
- Fix another bug where some videos dont have a duration value.
- Clean up some duplicated code.
> Fix video language detection

- tools/remove_wrong_language_videos.py
- tools/remove_wrong_videos.py
- zeeguu/core/youtube_api/youtube_api.py
Created a script that removes all the videos that are: 
- detected to be in the wrong language based on title and description.
- detected to have too few words for the duration of the video. (We have set the cutoff to one word per second based on average talking speed and looking through videos)
run the 'remove_wrong_videos.py' in the tools folder.
> remove wrong videos
